[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.cursor]
cursor = "0xeeeeee"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
background = "0x000000"
foreground = "0xeeeeee"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 10.0

[font.normal]
family = "Hack"

[window]
opacity = 0.9

[window.padding]
x = 8
y = 6

[keyboard]
bindings = [ { key = "ArrowUp", mods = "Shift", action="ScrollLineUp" }, { key = "ArrowDown", mods = "Shift", action = "ScrollLineDown" } ]
